import e2e from '../e2e/setup.js';

export default async function setup(globalConfig) {
  e2e(globalConfig);
}

/*
{
  bail: 0,
  changedFilesWithAncestor: false,
  changedSince: undefined,
  collectCoverage: false,
  collectCoverageFrom: [],
  collectCoverageOnlyFrom: undefined,
  coverageDirectory: '/Users/vscheuber/Projects/frodo/coverage',
  coverageProvider: 'babel',
  coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
  coverageThreshold: undefined,
  detectLeaks: false,
  detectOpenHandles: false,
  errorOnDeprecated: false,
  expand: false,
  filter: undefined,
  findRelatedTests: false,
  forceExit: false,
  globalSetup: '/Users/vscheuber/Projects/frodo/test/global/global-setup.js',
  globalTeardown: undefined,
  json: false,
  lastCommit: false,
  listTests: false,
  logHeapUsage: false,
  maxConcurrency: 5,
  maxWorkers: 15,
  noSCM: undefined,
  noStackTrace: false,
  nonFlagArgs: [ 'e2e' ],
  notify: false,
  notifyMode: 'failure-change',
  onlyChanged: false,
  onlyFailures: false,
  outputFile: undefined,
  passWithNoTests: false,
  projects: [],
  replname: undefined,
  reporters: undefined,
  rootDir: '/Users/vscheuber/Projects/frodo',
  runTestsByPath: false,
  silent: undefined,
  skipFilter: false,
  snapshotFormat: undefined,
  testFailureExitCode: 1,
  testNamePattern: undefined,
  testPathPattern: 'e2e',
  testResultsProcessor: undefined,
  testSequencer: '/Users/vscheuber/Projects/frodo/node_modules/@jest/test-sequencer/build/index.js',
  testTimeout: undefined,
  updateSnapshot: 'new',
  useStderr: false,
  verbose: true,
  watch: false,
  watchAll: false,
  watchPlugins: undefined,
  watchman: true
}
*/
