export type AnyNodeTypes =
    "AcceptTermsAndConditionsNode" |
    "AccountActiveDecisionNode" |
    "AccountLockoutNode" |
    "AgentDataStoreDecisionNode" |
    "AnonymousSessionUpgradeNode" |
    "AnonymousUserNode" |
    "AttributeCollectorNode" |
    "AttributePresentDecisionNode" |
    "AttributeValueDecisionNode" |
    "AuthLevelDecisionNode" |
    "ChoiceCollectorNode" |
    "ConsentNode" |
    "CookiePresenceDecisionNode" |
    "CreateObjectNode" |
    "CreatePasswordNode" |
    "DataStoreDecisionNode" |
    "DeviceGeoFencingNode" |
    "DeviceLocationMatchNode" |
    "DeviceMatchNode" |
    "DeviceProfileCollectorNode" |
    "DeviceSaveNode" |
    "DeviceTamperingVerificationNode" |
    "DisplayUserNameNode" |
    "EmailSuspendNode" |
    "EmailTemplateNode" |
    "IdentifyExistingUserNode" |
    "IncrementLoginCountNode" |
    "InnerTreeEvaluatorNode" |
    "IotAuthenticationNode" |
    "IotRegistrationNode" |
    "KbaCreateNode" |
    "KbaDecisionNode" |
    "KbaVerifyNode" |
    "LdapDecisionNode" |
    "LoginCountDecisionNode" |
    "MessageNode" |
    "MetadataNode" |
    "MeterNode" |
    "ModifyAuthLevelNode" |
    "OneTimePasswordCollectorDecisionNode" |
    "OneTimePasswordGeneratorNode" |
    "OneTimePasswordSmsSenderNode" |
    "OneTimePasswordSmtpSenderNode" |
    "PageNode" |
    "PasswordCollectorNode" |
    "PatchObjectNode" |
    "PersistentCookieDecisionNode" |
    "PollingWaitNode" |
    "ProfileCompletenessDecisionNode" |
    "ProvisionDynamicAccountNode" |
    "ProvisionIdmAccountNode" |
    "PushAuthenticationSenderNode" |
    "PushResultVerifierNode" |
    "QueryFilterDecisionNode" |
    "RecoveryCodeCollectorDecisionNode" |
    "RecoveryCodeDisplayNode" |
    "RegisterLogoutWebhookNode" |
    "RemoveSessionPropertiesNode" |
    "RequiredAttributesDecisionNode" |
    "RetryLimitDecisionNode" |
    "ScriptedDecisionNode" |
    "SelectIdPNode" |
    "SessionDataNode" |
    "SetFailureUrlNode" |
    "SetPersistentCookieNode" |
    "SetSessionPropertiesNode" |
    "SetSuccessUrlNode" |
    "SocialFacebookNode" |
    "SocialGoogleNode" |
    "SocialNode" |
    "SocialOAuthIgnoreProfileNode" |
    "SocialOpenIdConnectNode" |
    "SocialProviderHandlerNode" |
    "TermsAndConditionsDecisionNode" |
    "TimeSinceDecisionNode" |
    "TimerStartNode" |
    "TimerStopNode" |
    "UsernameCollectorNode" |
    "ValidatedPasswordNode" |
    "ValidatedUsernameNode" |
    "WebAuthnAuthenticationNode" |
    "WebAuthnDeviceStorageNode" |
    "WebAuthnRegistrationNode" |
    "ZeroPageLoginNode" |
    "product-CertificateCollectorNode" |
    "product-CertificateUserExtractorNode" |
    "product-CertificateValidationNode" |
    "product-KerberosNode" |
    "product-ReCaptchaNode" |
    "product-Saml2Node" |
    "product-WriteFederationInformationNode" |
    "PushRegistrationNode" |
    "GetAuthenticatorAppNode" |
    "MultiFactorRegistrationOptionsNode" |
    "OptOutMultiFactorAuthenticationNode" |
    "OathRegistrationNode" |
    "OathTokenVerifierNode" |
    "PassthroughAuthenticationNode" |
    "ConfigProviderNode" |
    "DebugNode" |
    "AbstractSocialAuthLoginNode"

export type AnyNodeTypesArr = Array<AnyNodeTypes>;