export const DEFAULT_REALM_KEY = '__default__realm__';
export const CLASSIC_DEPLOYMENT_TYPE_KEY = 'classic';
export const CLOUD_DEPLOYMENT_TYPE_KEY = 'cloud';
export const FORGEOPS_DEPLOYMENT_TYPE_KEY = 'forgeops';
export const DEPLOYMENT_TYPES = [
  CLASSIC_DEPLOYMENT_TYPE_KEY,
  CLOUD_DEPLOYMENT_TYPE_KEY,
  FORGEOPS_DEPLOYMENT_TYPE_KEY,
];
export const DEPLOYMENT_TYPE_REALM_MAP = {
  [CLASSIC_DEPLOYMENT_TYPE_KEY]: '/',
  [CLOUD_DEPLOYMENT_TYPE_KEY]: 'alpha',
  [FORGEOPS_DEPLOYMENT_TYPE_KEY]: '/',
};
export const FRODO_METADATA_ID = 'frodo';
